apiVersion: v1
kind: PersistentVolume
metadata:
  name: langflow-pv
  namespace: aipns
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /var/lib/langflow-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langflow-pvc
  namespace: aipns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: langflow-pv
